<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
        .company-name { font-size: 24px; font-weight: bold; }
        .report-title { font-size: 18px; margin-top: 10px; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f3f4f6; }
        .footer { position: fixed; bottom: 0; width: 100%; border-top: 1px solid #ddd; padding-top: 5px; text-align: center; font-size: 10px; color: #777; }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">{{ $company->name ?? 'Larasoft Default Company' }}</div>
        <div class="report-title">{{ $title }}</div>
    </div>

    @foreach($records as $record)
        <div style="margin-bottom: 30px; page-break-inside: avoid;">
            <h3>{{ $def->nameGet($record) }}</h3>
            <table>
                <tbody>
                    @foreach($fields as $fname => $fdef)
                        @if(!($fdef['invisible'] ?? false) && $record->$fname !== null)
                            <tr>
                                <th style="width: 30%;">{{ $fdef['string'] ?? $fname }}</th>
                                <td>
                                    @if(is_array($record->$fname) || is_object($record->$fname))
                                        {{ json_encode($record->$fname) }}
                                    @else
                                        {{ $record->$fname }}
                                    @endif
                                </td>
                            </tr>
                        @endif
                    @endforeach
                </tbody>
            </table>
        </div>
    @endforeach

    <div class="footer">
        Generated by Larasoft ERP
    </div>
</body>
</html>
